/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package com.xpn.xwiki.it.selenium.xem;

import com.xpn.xwiki.it.selenium.framework.AbstractXWikiTestCase;
import com.xpn.xwiki.it.selenium.framework.AlbatrossSkinExecutor;
import com.xpn.xwiki.it.selenium.framework.XWikiTestSuite;

import junit.framework.Test;

/**
 * Minimum test that just try to access wiki.
 * 
 * @version $Id: $
 */
public class WikiManagementCreate extends AbstractXWikiTestCase
{
    public static Test suite()
    {
        XWikiTestSuite suite = new XWikiTestSuite("Verify xem starting");
        suite.addTestSuite(WikiManagementCreate.class, AlbatrossSkinExecutor.class);
        return suite;
    }

    /**
     * {@inheritDoc}
     * 
     * @see com.xpn.xwiki.it.selenium.framework.AbstractXWikiTestCase#setUp()
     */
    @Override
    public void setUp() throws Exception
    {
        super.setUp();
        loginAsAdmin();

        open("/xwiki/bin/WikiManager/CreateNewWiki");
    }
    
    /**
     * Validate empty wiki creation and all automated actions around it.
     */
    public void testCreateEmptyWiki()
    {
        setWikiNameFieldValue();
        setFieldValue("XWiki.XWikiServerClass_0_description", "A new empty wiki");
        submit();

        // Validate creation finished with no error
        assertTextPresent("Your wiki \"newemptywiki\" has been created.");

        open("/xwiki/bin/WikiManager/");

        // Validate the new wiki is listed
        assertTextPresent("newemptywiki");
        // Validate the autogenerated pretty name
        assertTextPresent("Newemptywiki");
        // Validate the correct domain is printed in the list
        assertTextPresent("newemptywiki.localdomain.com");
    }
    
    /**
     * Validate the ajax based wiki name validation.
     */
    private void setWikiNameFieldValue()
    {
        // Validate that an existing wiki name is invalid as wiki name
        setFieldValue("wikiname", "xwiki");
        getSelenium().keyUp("wikiname", "\\40");
        assertTextPresent("This identifier is already used");

        // Validate that "" is invalid as wiki name
        setFieldValue("wikiname", "");
        getSelenium().keyUp("wikiname", "\\40");
        assertTextPresent("Identifier can't be empty");

        // Validate that a not existing wiki name is valid as wiki name
        setFieldValue("wikiname", "newemptywiki");
        getSelenium().keyUp("wikiname", "\\40");
        assertTextPresent("You can use this name as new wiki identifier");
    }
}
